### ISSUE TITLE
ForLoop stores and does not clear data in RAM after each loop

### ISSUE THREAD

**Issue by Shyryp** [BadCafeCode/execution-inversion-demo-comfyui#8]
I have created a workflow with ForLoop that uses Inpaint Crop to create a temporary image while editing. When ForLoopEnd is reached, the stale data created by Inpaint Crop is not cleared from memory.

More details:
https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/issues/32

@guill How is memory clearing supposed to be done in a loop?
Is this a problem with ForLoop functionality or is it a problem with Inpaint Crop from a private package?

**Comment by Shyryp** [comment]
Also, what was generated inside ForLoop is not removed from memory even after the queue is finished.

**Comment by guill** [comment]
> 
> @guill How is memory clearing supposed to be done in a loop?
> Is this a problem with ForLoop functionality or is it a problem with Inpaint Crop from a private package?
> 

Currently, nodes created at runtime (like those within a loop) are cached just like any other node. The results will be removed from memory when you run a workflow that doesn't contain the loop.

If you have a concrete use-case/workflow where this is causing issues, please post it as an issue on the main ComfyUI repo and tag me. We discussed implementing more aggressive cache pruning, but wanted to wait and see whether it was actually an issue before introducing the complexity.

It's possible this is due to a custom node doing something wonky -- if somebody is storing a large object on each node instance, having N copies (for a loop that runs N times) could add up. It's also possible (if you are looping many times) that just the contents of the cache itself is overwhelming your machine. If you post a workflow, I can take a look.

**Comment by Shyryp** [comment]
I'm closing the issue as the discussion has been moved to the ComfyUI repository.
